/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PublicRouteImport } from './routes/public'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as PublicIndexRouteImport } from './routes/public/index'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as PublicTrainersRouteImport } from './routes/public/trainers'
import { Route as PublicProgramsRouteImport } from './routes/public/programs'
import { Route as PublicAboutRouteImport } from './routes/public/about'
import { Route as AppDashboardWorkoutPlannerRouteImport } from './routes/_app/dashboard/workout-planner'
import { Route as AppDashboardTransformationRouteImport } from './routes/_app/dashboard/transformation'
import { Route as AppDashboardStrengthRouteImport } from './routes/_app/dashboard/strength'
import { Route as AppDashboardSettingsRouteImport } from './routes/_app/dashboard/settings'
import { Route as AppDashboardRecoveryRouteImport } from './routes/_app/dashboard/recovery'
import { Route as AppDashboardMealPlannerRouteImport } from './routes/_app/dashboard/meal-planner'
import { Route as AppDashboardLiveRouteImport } from './routes/_app/dashboard/live'
import { Route as AppDashboardInjurySafeRouteImport } from './routes/_app/dashboard/injury-safe'
import { Route as AppDashboardHealthTrackerRouteImport } from './routes/_app/dashboard/health-tracker'
import { Route as AppDashboardGamificationRouteImport } from './routes/_app/dashboard/gamification'
import { Route as AppDashboardExercisesRouteImport } from './routes/_app/dashboard/exercises'
import { Route as AppDashboardCoachRouteImport } from './routes/_app/dashboard/coach'
import { Route as AppDashboardChallengesRouteImport } from './routes/_app/dashboard/challenges'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/public',
  path: '/public',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const PublicTrainersRoute = PublicTrainersRouteImport.update({
  id: '/trainers',
  path: '/trainers',
  getParentRoute: () => PublicRoute,
} as any)
const PublicProgramsRoute = PublicProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRoute,
} as any)
const AppDashboardWorkoutPlannerRoute =
  AppDashboardWorkoutPlannerRouteImport.update({
    id: '/dashboard/workout-planner',
    path: '/dashboard/workout-planner',
    getParentRoute: () => AppRoute,
  } as any)
const AppDashboardTransformationRoute =
  AppDashboardTransformationRouteImport.update({
    id: '/dashboard/transformation',
    path: '/dashboard/transformation',
    getParentRoute: () => AppRoute,
  } as any)
const AppDashboardStrengthRoute = AppDashboardStrengthRouteImport.update({
  id: '/dashboard/strength',
  path: '/dashboard/strength',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardSettingsRoute = AppDashboardSettingsRouteImport.update({
  id: '/dashboard/settings',
  path: '/dashboard/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRecoveryRoute = AppDashboardRecoveryRouteImport.update({
  id: '/dashboard/recovery',
  path: '/dashboard/recovery',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardMealPlannerRoute = AppDashboardMealPlannerRouteImport.update({
  id: '/dashboard/meal-planner',
  path: '/dashboard/meal-planner',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardLiveRoute = AppDashboardLiveRouteImport.update({
  id: '/dashboard/live',
  path: '/dashboard/live',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardInjurySafeRoute = AppDashboardInjurySafeRouteImport.update({
  id: '/dashboard/injury-safe',
  path: '/dashboard/injury-safe',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardHealthTrackerRoute =
  AppDashboardHealthTrackerRouteImport.update({
    id: '/dashboard/health-tracker',
    path: '/dashboard/health-tracker',
    getParentRoute: () => AppRoute,
  } as any)
const AppDashboardGamificationRoute =
  AppDashboardGamificationRouteImport.update({
    id: '/dashboard/gamification',
    path: '/dashboard/gamification',
    getParentRoute: () => AppRoute,
  } as any)
const AppDashboardExercisesRoute = AppDashboardExercisesRouteImport.update({
  id: '/dashboard/exercises',
  path: '/dashboard/exercises',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardCoachRoute = AppDashboardCoachRouteImport.update({
  id: '/dashboard/coach',
  path: '/dashboard/coach',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardChallengesRoute = AppDashboardChallengesRouteImport.update({
  id: '/dashboard/challenges',
  path: '/dashboard/challenges',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/public': typeof PublicRouteWithChildren
  '/signup': typeof SignupRoute
  '/public/about': typeof PublicAboutRoute
  '/public/programs': typeof PublicProgramsRoute
  '/public/trainers': typeof PublicTrainersRoute
  '/public/': typeof PublicIndexRoute
  '/dashboard/challenges': typeof AppDashboardChallengesRoute
  '/dashboard/coach': typeof AppDashboardCoachRoute
  '/dashboard/exercises': typeof AppDashboardExercisesRoute
  '/dashboard/gamification': typeof AppDashboardGamificationRoute
  '/dashboard/health-tracker': typeof AppDashboardHealthTrackerRoute
  '/dashboard/injury-safe': typeof AppDashboardInjurySafeRoute
  '/dashboard/live': typeof AppDashboardLiveRoute
  '/dashboard/meal-planner': typeof AppDashboardMealPlannerRoute
  '/dashboard/recovery': typeof AppDashboardRecoveryRoute
  '/dashboard/settings': typeof AppDashboardSettingsRoute
  '/dashboard/strength': typeof AppDashboardStrengthRoute
  '/dashboard/transformation': typeof AppDashboardTransformationRoute
  '/dashboard/workout-planner': typeof AppDashboardWorkoutPlannerRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/public/about': typeof PublicAboutRoute
  '/public/programs': typeof PublicProgramsRoute
  '/public/trainers': typeof PublicTrainersRoute
  '/': typeof AppIndexRoute
  '/public': typeof PublicIndexRoute
  '/dashboard/challenges': typeof AppDashboardChallengesRoute
  '/dashboard/coach': typeof AppDashboardCoachRoute
  '/dashboard/exercises': typeof AppDashboardExercisesRoute
  '/dashboard/gamification': typeof AppDashboardGamificationRoute
  '/dashboard/health-tracker': typeof AppDashboardHealthTrackerRoute
  '/dashboard/injury-safe': typeof AppDashboardInjurySafeRoute
  '/dashboard/live': typeof AppDashboardLiveRoute
  '/dashboard/meal-planner': typeof AppDashboardMealPlannerRoute
  '/dashboard/recovery': typeof AppDashboardRecoveryRoute
  '/dashboard/settings': typeof AppDashboardSettingsRoute
  '/dashboard/strength': typeof AppDashboardStrengthRoute
  '/dashboard/transformation': typeof AppDashboardTransformationRoute
  '/dashboard/workout-planner': typeof AppDashboardWorkoutPlannerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/public': typeof PublicRouteWithChildren
  '/signup': typeof SignupRoute
  '/public/about': typeof PublicAboutRoute
  '/public/programs': typeof PublicProgramsRoute
  '/public/trainers': typeof PublicTrainersRoute
  '/_app/': typeof AppIndexRoute
  '/public/': typeof PublicIndexRoute
  '/_app/dashboard/challenges': typeof AppDashboardChallengesRoute
  '/_app/dashboard/coach': typeof AppDashboardCoachRoute
  '/_app/dashboard/exercises': typeof AppDashboardExercisesRoute
  '/_app/dashboard/gamification': typeof AppDashboardGamificationRoute
  '/_app/dashboard/health-tracker': typeof AppDashboardHealthTrackerRoute
  '/_app/dashboard/injury-safe': typeof AppDashboardInjurySafeRoute
  '/_app/dashboard/live': typeof AppDashboardLiveRoute
  '/_app/dashboard/meal-planner': typeof AppDashboardMealPlannerRoute
  '/_app/dashboard/recovery': typeof AppDashboardRecoveryRoute
  '/_app/dashboard/settings': typeof AppDashboardSettingsRoute
  '/_app/dashboard/strength': typeof AppDashboardStrengthRoute
  '/_app/dashboard/transformation': typeof AppDashboardTransformationRoute
  '/_app/dashboard/workout-planner': typeof AppDashboardWorkoutPlannerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/public'
    | '/signup'
    | '/public/about'
    | '/public/programs'
    | '/public/trainers'
    | '/public/'
    | '/dashboard/challenges'
    | '/dashboard/coach'
    | '/dashboard/exercises'
    | '/dashboard/gamification'
    | '/dashboard/health-tracker'
    | '/dashboard/injury-safe'
    | '/dashboard/live'
    | '/dashboard/meal-planner'
    | '/dashboard/recovery'
    | '/dashboard/settings'
    | '/dashboard/strength'
    | '/dashboard/transformation'
    | '/dashboard/workout-planner'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/public/about'
    | '/public/programs'
    | '/public/trainers'
    | '/'
    | '/public'
    | '/dashboard/challenges'
    | '/dashboard/coach'
    | '/dashboard/exercises'
    | '/dashboard/gamification'
    | '/dashboard/health-tracker'
    | '/dashboard/injury-safe'
    | '/dashboard/live'
    | '/dashboard/meal-planner'
    | '/dashboard/recovery'
    | '/dashboard/settings'
    | '/dashboard/strength'
    | '/dashboard/transformation'
    | '/dashboard/workout-planner'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/public'
    | '/signup'
    | '/public/about'
    | '/public/programs'
    | '/public/trainers'
    | '/_app/'
    | '/public/'
    | '/_app/dashboard/challenges'
    | '/_app/dashboard/coach'
    | '/_app/dashboard/exercises'
    | '/_app/dashboard/gamification'
    | '/_app/dashboard/health-tracker'
    | '/_app/dashboard/injury-safe'
    | '/_app/dashboard/live'
    | '/_app/dashboard/meal-planner'
    | '/_app/dashboard/recovery'
    | '/_app/dashboard/settings'
    | '/_app/dashboard/strength'
    | '/_app/dashboard/transformation'
    | '/_app/dashboard/workout-planner'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  PublicRoute: typeof PublicRouteWithChildren
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public': {
      id: '/public'
      path: '/public'
      fullPath: '/public'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public/': {
      id: '/public/'
      path: '/'
      fullPath: '/public/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/public/trainers': {
      id: '/public/trainers'
      path: '/trainers'
      fullPath: '/public/trainers'
      preLoaderRoute: typeof PublicTrainersRouteImport
      parentRoute: typeof PublicRoute
    }
    '/public/programs': {
      id: '/public/programs'
      path: '/programs'
      fullPath: '/public/programs'
      preLoaderRoute: typeof PublicProgramsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/public/about': {
      id: '/public/about'
      path: '/about'
      fullPath: '/public/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_app/dashboard/workout-planner': {
      id: '/_app/dashboard/workout-planner'
      path: '/dashboard/workout-planner'
      fullPath: '/dashboard/workout-planner'
      preLoaderRoute: typeof AppDashboardWorkoutPlannerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard/transformation': {
      id: '/_app/dashboard/transformation'
      path: '/dashboard/transformation'
      fullPath: '/dashboard/transformation'
      preLoaderRoute: typeof AppDashboardTransformationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard/strength': {
      id: '/_app/dashboard/strength'
      path: '/dashboard/strength'
      fullPath: '/dashboard/strength'
      preLoaderRoute: typeof AppDashboardStrengthRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard/settings': {
      id: '/_app/dashboard/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AppDashboardSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard/recovery': {
      id: '/_app/dashboard/recovery'
      path: '/dashboard/recovery'
      fullPath: '/dashboard/recovery'
      preLoaderRoute: typeof AppDashboardRecoveryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard/meal-planner': {
      id: '/_app/dashboard/meal-planner'
      path: '/dashboard/meal-planner'
      fullPath: '/dashboard/meal-planner'
      preLoaderRoute: typeof AppDashboardMealPlannerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard/live': {
      id: '/_app/dashboard/live'
      path: '/dashboard/live'
      fullPath: '/dashboard/live'
      preLoaderRoute: typeof AppDashboardLiveRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard/injury-safe': {
      id: '/_app/dashboard/injury-safe'
      path: '/dashboard/injury-safe'
      fullPath: '/dashboard/injury-safe'
      preLoaderRoute: typeof AppDashboardInjurySafeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard/health-tracker': {
      id: '/_app/dashboard/health-tracker'
      path: '/dashboard/health-tracker'
      fullPath: '/dashboard/health-tracker'
      preLoaderRoute: typeof AppDashboardHealthTrackerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard/gamification': {
      id: '/_app/dashboard/gamification'
      path: '/dashboard/gamification'
      fullPath: '/dashboard/gamification'
      preLoaderRoute: typeof AppDashboardGamificationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard/exercises': {
      id: '/_app/dashboard/exercises'
      path: '/dashboard/exercises'
      fullPath: '/dashboard/exercises'
      preLoaderRoute: typeof AppDashboardExercisesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard/coach': {
      id: '/_app/dashboard/coach'
      path: '/dashboard/coach'
      fullPath: '/dashboard/coach'
      preLoaderRoute: typeof AppDashboardCoachRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard/challenges': {
      id: '/_app/dashboard/challenges'
      path: '/dashboard/challenges'
      fullPath: '/dashboard/challenges'
      preLoaderRoute: typeof AppDashboardChallengesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppDashboardChallengesRoute: typeof AppDashboardChallengesRoute
  AppDashboardCoachRoute: typeof AppDashboardCoachRoute
  AppDashboardExercisesRoute: typeof AppDashboardExercisesRoute
  AppDashboardGamificationRoute: typeof AppDashboardGamificationRoute
  AppDashboardHealthTrackerRoute: typeof AppDashboardHealthTrackerRoute
  AppDashboardInjurySafeRoute: typeof AppDashboardInjurySafeRoute
  AppDashboardLiveRoute: typeof AppDashboardLiveRoute
  AppDashboardMealPlannerRoute: typeof AppDashboardMealPlannerRoute
  AppDashboardRecoveryRoute: typeof AppDashboardRecoveryRoute
  AppDashboardSettingsRoute: typeof AppDashboardSettingsRoute
  AppDashboardStrengthRoute: typeof AppDashboardStrengthRoute
  AppDashboardTransformationRoute: typeof AppDashboardTransformationRoute
  AppDashboardWorkoutPlannerRoute: typeof AppDashboardWorkoutPlannerRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppDashboardChallengesRoute: AppDashboardChallengesRoute,
  AppDashboardCoachRoute: AppDashboardCoachRoute,
  AppDashboardExercisesRoute: AppDashboardExercisesRoute,
  AppDashboardGamificationRoute: AppDashboardGamificationRoute,
  AppDashboardHealthTrackerRoute: AppDashboardHealthTrackerRoute,
  AppDashboardInjurySafeRoute: AppDashboardInjurySafeRoute,
  AppDashboardLiveRoute: AppDashboardLiveRoute,
  AppDashboardMealPlannerRoute: AppDashboardMealPlannerRoute,
  AppDashboardRecoveryRoute: AppDashboardRecoveryRoute,
  AppDashboardSettingsRoute: AppDashboardSettingsRoute,
  AppDashboardStrengthRoute: AppDashboardStrengthRoute,
  AppDashboardTransformationRoute: AppDashboardTransformationRoute,
  AppDashboardWorkoutPlannerRoute: AppDashboardWorkoutPlannerRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface PublicRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicProgramsRoute: typeof PublicProgramsRoute
  PublicTrainersRoute: typeof PublicTrainersRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicProgramsRoute: PublicProgramsRoute,
  PublicTrainersRoute: PublicTrainersRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  PublicRoute: PublicRouteWithChildren,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
